# Generated by Django 4.0.1 on 2022-01-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='superhost',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
